apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    url: http://host.docker.internal:9090
    access: proxy
    editable: true

  - name: Loki
    type: loki
    url: http://host.docker.internal:3100
    access: proxy
    editable: false
    isDefault: true