version: '3'

services: 
  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: "orderservice_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  order_service:
    container_name: order_service
    build: ./
    ports:
      - 8000:80
    environment:
      - POSTGRES_URL=postgresql+psycopg2://postgres:postgres@postgres:5432/orderservice_db
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672/
  
